import type { Metadata } from "next";
import { headers } from "next/headers";
import { Inter } from "next/font/google";

import { RootLayout } from "@/lib/config";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayout wagmiCookie={headers().get("cookie")}>
          {children}
        </RootLayout>
        {/* <RootLayout wagmiCookie={"fsdf"}>{children}</RootLayout> */}
      </body>
    </html>
  );
}
